name: Load Testing Pipline

on:
    push:
        branches:
            - master

jobs:
    Load-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: 16

            - name: Install dependences
              run: npm install

            - name: Install K6
              run: sudo snap install k6

            - name: start app
              run: |
                npm start &
                sleep 5
 
            - name: Run Load Testing
              run: k6 run load-test.js

            
